paths:
  api_server: /home/mainserver/minecraft/MineApi/src/config
  minecraft_server: /home/mainserver/minecraft/bedrock-server
messages:
  welcome: ''
  news: ''
  farewell: ''
state:
  activeWorld: Bedrock level

